spring:
  h2.console:
    path: /h2
    enabled: true
  datasource:
    hikari.jdbc-url: jdbc:h2:mem:testdb

graphql:
  servlet:
    mapping: /graphql

graphiql:
  endpoint: /graphql
  mapping: /graphiql-ui